
title: Cherub Fund - Angel Funding for seed rounds
description: >- # this means to ignore newlines until "baseurl:"
  Cherub Fund - Angel Funding for seed rounds
url: "cherubfund.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ainc

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
